apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-c
        image: tonyq2k3/mern-stack-frontend:467870c0027b7ddbc8c95e02107fc7a7313c648e
        env:
          - name: REACT_APP_API
            valueFrom:
              configMapKeyRef:
                name: api-configmap
                key: gateway_url
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
        ports:
        - containerPort: 3000